### ISSUE TITLE
Java 16 support

### ISSUE THREAD

**Issue by louhy** [amogilev/yagson#6]
I haven't looked into it much, but I think there might be a problem with Java 16 support. This problem could start as early as Java 12 - I only checked 11 and 16. 

Using this to initialize: 
`new YaGsonBuilder().excludeFieldsWithModifiers(Modifier.TRANSIENT, Modifier.STATIC, Modifier.VOLATILE);`

```
Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
	at com.gilecode.yagson.com.google.gson.internal.Excluder.<clinit>(Excluder.java:71)
	at com.gilecode.yagson.com.google.gson.GsonBuilder.<init>(GsonBuilder.java:79)
	at com.gilecode.yagson.YaGsonBuilder.<init>(YaGsonBuilder.java:36)

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final transient java.lang.Class java.util.EnumSet.elementType accessible: module java.base does not "opens java.util" to unnamed module @19e0a4f6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.gilecode.yagson.com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.gilecode.yagson.types.TypeUtils.getDeclaredFieldNoChecks(TypeUtils.java:400)
	at com.gilecode.yagson.types.TypeUtils.getDeclaredField(TypeUtils.java:418)
	at com.gilecode.yagson.types.TypeUtils.<clinit>(TypeUtils.java:456)

```

**Comment by amogilev** [comment]
Hi,

You are absolutely right. Unfortunately, modern Java have chose a way that is less and less compatible with the "universal" serialization YaGson provides. Since version 9 it issues warnings, at some later version it throws exception :-(

Unfortunately, there is no fix for the issue. I an going to update README with a compatibility warning about that.

Thank you for drawing my attention to this issue!

**Comment by louhy** [comment]
Yeah, I was afraid of that I guess. I don't get their logic that they need to lock down and hide things previously accessible as internal API, because accessing that internal API might break things as JDKs evolve over time. The "solution" just breaks everything right up front! Or maybe it is more complicated and I just don't understand the reasoning... :unamused:

**Comment by louhy** [comment]
That said - this library _does_ work on Java 11 for me. It's past that where the breakage occurs. So you could probably support things up at least until 11 (at least it has a few years of support left being an LTS version).

**Comment by amogilev** [comment]
I am not going to remove this library. I know a lot of developers and companies who still use Java 8.

I understand that the library work on Java 11. However, as I have noted in the README, in Java 9-11 there could be "Illegal reflective access" warning printed (and some guys considered it as a bug).

Actually, if a developer is in control of the application's command line, it is still possible to use YaGson in Java 16+. For example, one can use command line options like "--add-opens" or "--patch-module". I guess I'll try using Java agent in future to allow reflection uses for YaGson in my "Spring MX" IDEA plugin (but not sure when I will have time for this....)

**Comment by louhy** [comment]
Of course, no reason to remove anything. Yeah I noticed the readme changes shortly after I commented, looks good.

**Comment by louhy** [comment]
@amogilev Turns out (at least in my case) the JVM parameters weren't so painful after all. 
Working well building with JDK 17 running in JRE 17 using these JVM parameters: 

```
--add-opens=java.base/java.util=ALL-UNNAMED 
--add-opens=java.base/java.time=ALL-UNNAMED
```

If others encounter similar but different errors, it probably won't be too hard figuring out what you need to do based on the error and the syntax above. This assumes your main project is non-modular.
